extends: [["spectral:oas", "all"]]
functions:
  - enum-has-description
  - private-must-have-401-403
  - has-request-body-must-have-400
  - has-2xx-response
  - server-id-must-be-readonly
  - client-id-must-not-be-readonly
  - property-must-have-description
rules:
  enum-has-description:
    message: "{{error}}"
    severity: error
    given:
      - "$.paths[*][*].parameters[*].schema"
      - "$.paths[*][*].requestBody.content[*].schema.properties[*]"
      - "$.paths[*][*].responses['200'].content[*].schema.properties[*]"
      - "$.components.schemas[*].properties[*]"
    then:
      function: enum-has-description

  private-endpoint-must-have-401-403:
    message: "{{error}}"
    severity: error
    given: "$.paths[*][*]"
    then: { function: private-must-have-401-403 }

  has-request-body-must-have-400:
    message: "{{error}}"
    severity: error
    given: "$.paths[*][*]"
    then: { function: has-request-body-must-have-400 }

  server-id-must-be-readonly:
    message: "{{error}}"
    severity: error
    given: "$.paths[*][*].responses['200'].content"
    then:
      function: server-id-must-be-readonly

  client-id-must-not-be-readonly:
    message: "{{error}}"
    severity: error
    given: "$.paths[*][*].requestBody.content"
    then:
      function: client-id-must-not-be-readonly

  property-must-have-description:
    message: "{{error}}"
    severity: warn
    given:
      - "$.components.schemas[*]"
      - "$.components.schemas[*].properties[*]"
      - "$.paths[*][*].requestBody.content[*].schema"
      - "$.paths[*][*].responses['200'].content[*].schema"
    then:
      function: property-must-have-description
# Rule
  path-kebab-case: 
    message: "Path phải dùng kebab-case." 
    severity: warn
    given: "$.paths.*~"
    then:
      function: pattern
      functionOptions:
        match: "^(/[a-z0-9-]+|/{[a-zA-Z0-9_]+})+$"

  operation-id-verb-noun:
      message: 'operationId "{{value}}" sai format, operationId phải dùng camelCase và bắt đầu bằng động từ — ví dụ: listUsers, createOrder, reopenTicket.'
      severity: error
      given: "$.paths[*][*].operationId"
      then:
        function: pattern
        functionOptions:
          match: "^[a-z][a-zA-Z0-9]+$"

  operation-must-have-description:
    message: "Operation phải có description."
    severity: warn
    given: "$.paths[*][*]"
    then:
      field: description
      function: truthy

  operation-with-id-must-have-404:
    message: "Operation với path parameter phải có response 404 (Not Found)."
    severity: warn
    given: "$.paths[?(@property.match('.*{.*}.*'))][get,put,patch,delete]"
    then:
      field: responses.404
      function: truthy

  post-must-have-2xx:
    message: "{{error}}"
    severity: warn
    given: "$.paths[*].post"
    then:
      function: has-2xx-response

  info-must-have-contact:
    message: "API phải có thông tin contact."
    severity: info
    given: "$.info"
    then:
      field: contact
      function: truthy

  delete-must-have-204:
    message: "DELETE nên trả 204 No Content."
    severity: warn
    given: "$.paths[*].delete"
    then:
      field: responses.204
      function: truthy

  operation-must-have-tags:
    message: "Operation phải có ít nhất 1 tag."
    severity: warn
    given: "$.paths[*][*]"
    then:
      field: tags
      function: schema
      functionOptions:
        schema:
          type: array
          minItems: 1
