openapi: "3.1.0"
info:
  title: PA Vietnam Support API
  version: "1.0.0"
  license:
    name: API
  description: API cho hệ thống ticket hỗ trợ khách hàng
  contact:
    name: PA Vietnam
    email: dev@pavietnam.vn

servers:
  - url: https://apigateway.pavietnam.vn
    description: Production

tags:
  - name: Ticket
    description: Các API liên quan đến ticket hỗ trợ khách hàng
  - name: Account
    description: Các API liên quan đến tài khoản
    
security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /v1/users/{user_id}/tickets:
    $ref: "./paths/ticket/create_tickets.yaml#/post"
  /v1/users/{user_id}/tickets/{id}:
    $ref: "./paths/ticket/get_ticket.yaml"
  /v1/users/{user_id}/tickets/{id}/close:
    $ref: "./paths/ticket/update_close.yaml"
  /v1/users/{user_id}/tickets/{id}/reopen:
    $ref: "./paths/ticket/create_reopen.yaml"
  /v1/users/{user_id}/tickets/{id}/conversations:
    $ref: "./paths/ticket/create_conversations.yaml"
  /v1/users/{user_id}/tickets/{ticket_id}/ratings:
    $ref: "./paths/ticket/create_ratings.yaml"
  /v1/users/{user_id}/tickets/{id}/feedback:
    $ref: "./paths/ticket/create_feedback.yaml"
  /v1/users/{user_id}/tickets/{id}/change-assignee:
    $ref: "./paths/ticket/create_change_assignee.yaml"